[settings]
experimental = true
lockfile = true

[tools]
actionlint = "1"
hk = "1"
jq = "1"
lua = "5.4"
pkl = "0"
shellcheck = "0"
shfmt = "3"
stylua = "2"
yamlfmt = "0"

[hooks]
postinstall = '''
if [ ${CI:-} == true ]; then
  mise run bootstrap-ci
else
  mise run bootstrap
fi
'''

# Tasks

[task_config]
includes = ["scripts"]

[tasks.bootstrap]
depends = ["_bootstrap_hk", "_bootstrap_luarocks"]

[tasks.bootstrap-ci]
depends = ["_bootstrap_luarocks"]

[tasks.check]
alias = ["chk", "lint"]
run = "hk check --all"

[tasks.fix]
alias = ["fmt", "format"]
run = "hk fix --all"

[tasks.test]
run = [{ task = "test-unit" }, { task = "test-integration" }]

[tasks.test-unit]
run = "lua tests/run_unit_tests.lua --verbose"

[tasks.test-integration]
run = "lua tests/run_integration_tests.lua --verbose"

# Hidden tasks

[tasks._bootstrap_hk]
hide = true
run = ["hk install --mise", { task = "update-hk-import" }]

[tasks._bootstrap_luarocks]
hide = true
run = [
  "luarocks install dkjson",
  "luarocks install luacheck",
  "luarocks install luaunit",
]
