[settings]
experimental = true

[task_config]
includes = ["scripts"]

[tools]
actionlint = "latest"
hk = "latest"
lua = "5.4"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
yamlfmt = "latest"

[plugins]
# Temporary fix for luarocks download and install issues
lua = "https://github.com/hisaac/vfox-lua.git#hisaac/fix-luarocks-download-and-install"

[hooks]
postinstall = "mise run bootstrap"

[tasks.bootstrap]
depends = ["_bootstrap_hk", "_bootstrap_luarocks"]

[tasks.check]
alias = ["chk", "lint"]
run = "hk check --all"

[tasks.fix]
alias = ["fmt", "format"]
run = "hk fix --all"

[tasks.test]
depends = ["test-unit", "test-integration"]

[tasks.test-unit]
run = "lua tests/run.lua"

# Hidden tasks

[tasks._bootstrap_hk]
hide = true
run = "hk install --mise"

[tasks._bootstrap_luarocks]
hide = true
run = ["luarocks install luacheck", "luarocks install luaunit"]
