[settings]
experimental = true
lockfile = true

[tools]
actionlint = "1"
hk = "1"
jq = "1"
lua = "5.4"
pkl = "0"
shellcheck = "0"
shfmt = "3"
stylua = "2"
yamlfmt = "0"

[hooks]
postinstall = '''
if [ "$CI" = "true" ]; then
  mise run bootstrap-ci
else
  mise run bootstrap
fi
'''

# Tasks

[task_config]
includes = ["scripts"]

[tasks.bootstrap]
depends = ["_bootstrap_hk", "_bootstrap_luarocks"]

[tasks.bootstrap-ci]
depends = ["_bootstrap_luarocks"]

[tasks.check]
alias = ["chk", "lint"]
run = "hk check --all"

[tasks.fix]
alias = ["fmt", "format"]
run = "hk fix --all"

[tasks.test]
run = [{ task = "test-unit" }, { task = "test-integration" }]

[tasks.test-unit]
run = "lua tests/run_unit_tests.lua --verbose"

[tasks.test-integration]
run = "bash tests/integration_tests.sh"

# Tool tasks

[tasks.upd]
description = "Upgrades outdated tools based on the range specified in mise.toml"
run = ["mise upgrade", "mise lock"]

[tasks.upg]
description = "Upgrades outdated tools to their latest versions, ignoring the range specified in mise.toml"
run = ["mise upgrade --bump", "mise lock"]

[tasks.outd]
run = "mise outdated --local --bump"


# Hidden tasks

[tasks._bootstrap_hk]
hide = true
run = ["hk install --mise", { task = "update-hk-import" }]

[tasks._bootstrap_luarocks]
hide = true
run = ["luarocks install luacheck", "luarocks install luaunit"]
