-- tests/test_version.lua
-- Unit tests for the Version module

-- Add lib directory to package path so we can require modules
package.path = package.path .. ";./lib/?.lua;./tests/?.lua"

local TestFramework = require("framework")
local Version = require("Version")

local test = TestFramework.new()

test:describe("Version.new()", function()
	test:it("should create a version from a simple version string", function()
		local v = Version.new("16")
		test:assert_equal(v.raw, "16")
		test:assert_equal(v.parts[1], 16)
		test:assert_equal(v.parts[2], 0)
		test:assert_equal(v.parts[3], 0)
		test:assert_equal(v.precision, 1)
	end)

	test:it("should create a version from a two-part version string", function()
		local v = Version.new("16.4")
		test:assert_equal(v.raw, "16.4")
		test:assert_equal(v.parts[1], 16)
		test:assert_equal(v.parts[2], 4)
		test:assert_equal(v.parts[3], 0)
		test:assert_equal(v.precision, 2)
	end)

	test:it("should create a version from a three-part version string", function()
		local v = Version.new("16.4.1")
		test:assert_equal(v.raw, "16.4.1")
		test:assert_equal(v.parts[1], 16)
		test:assert_equal(v.parts[2], 4)
		test:assert_equal(v.parts[3], 1)
		test:assert_equal(v.precision, 3)
	end)

	test:it("should handle version strings with more than three parts", function()
		local v = Version.new("16.4.1.2")
		test:assert_equal(v.precision, 4)
		-- Parts are padded to 3, so only first 3 parts are stored in parts array
		test:assert_equal(v.parts[1], 16)
		test:assert_equal(v.parts[2], 4)
		test:assert_equal(v.parts[3], 1)
	end)
end)

test:describe("Version:__lt (less than)", function()
	test:it("should compare major versions correctly", function()
		local v1 = Version.new("15.0.0")
		local v2 = Version.new("16.0.0")
		test:assert_true(v1 < v2)
		test:assert_false(v2 < v1)
	end)

	test:it("should compare minor versions correctly", function()
		local v1 = Version.new("16.3.0")
		local v2 = Version.new("16.4.0")
		test:assert_true(v1 < v2)
		test:assert_false(v2 < v1)
	end)

	test:it("should compare patch versions correctly", function()
		local v1 = Version.new("16.4.0")
		local v2 = Version.new("16.4.1")
		test:assert_true(v1 < v2)
		test:assert_false(v2 < v1)
	end)

	test:it("should return false for equal versions", function()
		local v1 = Version.new("16.4.1")
		local v2 = Version.new("16.4.1")
		test:assert_false(v1 < v2)
		test:assert_false(v2 < v1)
	end)
end)

test:describe("Version:__eq (equality)", function()
	test:it("should return true for equal versions", function()
		local v1 = Version.new("16.4.1")
		local v2 = Version.new("16.4.1")
		test:assert_true(v1 == v2)
	end)

	test:it("should return false for different versions", function()
		local v1 = Version.new("16.4.0")
		local v2 = Version.new("16.4.1")
		test:assert_false(v1 == v2)
	end)

	test:it("should handle versions with different precision", function()
		local v1 = Version.new("16")
		local v2 = Version.new("16.0.0")
		test:assert_true(v1 == v2, "16 should equal 16.0.0")
	end)
end)

test:describe("Version:__tostring", function()
	test:it("should convert version to string", function()
		local v = Version.new("16.4.1")
		test:assert_equal(tostring(v), "16.4.1")
	end)

	test:it("should show padded zeros", function()
		local v = Version.new("16")
		test:assert_equal(tostring(v), "16.0.0")
	end)
end)

test:describe("Version:matches_fuzzy", function()
	test:it("should match when query has precision 1 (major only)", function()
		local v = Version.new("16.4.1")
		local query = Version.new("16")
		test:assert_true(v:matches_fuzzy(query))
	end)

	test:it("should not match when major differs", function()
		local v = Version.new("15.4.1")
		local query = Version.new("16")
		test:assert_false(v:matches_fuzzy(query))
	end)

	test:it("should match when query has precision 2 (major.minor)", function()
		local v = Version.new("16.4.1")
		local query = Version.new("16.4")
		test:assert_true(v:matches_fuzzy(query))
	end)

	test:it("should not match when minor differs", function()
		local v = Version.new("16.3.1")
		local query = Version.new("16.4")
		test:assert_false(v:matches_fuzzy(query))
	end)

	test:it("should match when query has precision 3 (major.minor.patch)", function()
		local v = Version.new("16.4.1")
		local query = Version.new("16.4.1")
		test:assert_true(v:matches_fuzzy(query))
	end)

	test:it("should not match when patch differs", function()
		local v = Version.new("16.4.0")
		local query = Version.new("16.4.1")
		test:assert_false(v:matches_fuzzy(query))
	end)

	test:it("should allow different patch when query precision is 2", function()
		local v1 = Version.new("16.4.0")
		local v2 = Version.new("16.4.1")
		local query = Version.new("16.4")
		test:assert_true(v1:matches_fuzzy(query))
		test:assert_true(v2:matches_fuzzy(query))
	end)
end)

-- Run tests and exit with appropriate code
local success = test:summary()
os.exit(success and 0 or 1)
