#!/usr/bin/env bash
#MISE description="Run plugin tests - install and execute tool"
set -euo pipefail

mise plugin link --force xcode .
mise cache clear
mise ls-remote xcode
# mise install xcode@1.0.0

# Capture and display the output while also verifying it
# output=$(mise exec "xcode@1.0.0" -- "xcode" --version)
# echo "xcode output: $output"

# if echo "$output" | grep -q 'xcode@1.0.0'; then
# 	echo "✓ Tests passed"
# else
# 	echo "✗ Test failed: expected version xcode@1.0.0"
# 	exit 1
# fi
